site_name: HIS4936 Final Project Starter
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2017 Jake Calhoun, Eric Dean, Patrick Barry'
repo_url: https://github.com/thePortus/his4936-starter/
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Credits: 'credits.md'
